[2025-06-01T17:52:34.680+0200] {processor.py:157} INFO - Started process (PID=27017) to work on /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T17:52:34.681+0200] {processor.py:829} INFO - Processing file /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-01T17:52:34.681+0200] {logging_mixin.py:154} INFO - [2025-06-01T17:52:34.681+0200] {dagbag.py:536} INFO - Filling up the DagBag from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T17:52:34.684+0200] {logging_mixin.py:154} INFO - [2025-06-01T17:52:34.683+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-01T17:52:34.684+0200] {logging_mixin.py:154} INFO - [2025-06-01T17:52:34.684+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-01T17:52:34.684+0200] {processor.py:841} WARNING - No viable dags retrieved from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T17:52:34.692+0200] {processor.py:179} INFO - Processing /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.014 seconds
[2025-06-01T17:53:34.272+0200] {processor.py:157} INFO - Started process (PID=27130) to work on /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T17:53:34.276+0200] {processor.py:829} INFO - Processing file /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-01T17:53:34.276+0200] {logging_mixin.py:154} INFO - [2025-06-01T17:53:34.276+0200] {dagbag.py:536} INFO - Filling up the DagBag from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T17:53:34.278+0200] {logging_mixin.py:154} INFO - [2025-06-01T17:53:34.278+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-01T17:53:34.278+0200] {logging_mixin.py:154} INFO - [2025-06-01T17:53:34.278+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-01T17:53:34.278+0200] {processor.py:841} WARNING - No viable dags retrieved from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T17:53:34.284+0200] {processor.py:179} INFO - Processing /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.014 seconds
[2025-06-01T17:54:18.232+0200] {processor.py:157} INFO - Started process (PID=27198) to work on /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T17:54:18.236+0200] {processor.py:829} INFO - Processing file /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-01T17:54:18.236+0200] {logging_mixin.py:154} INFO - [2025-06-01T17:54:18.236+0200] {dagbag.py:536} INFO - Filling up the DagBag from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T17:54:18.238+0200] {logging_mixin.py:154} INFO - [2025-06-01T17:54:18.238+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-01T17:54:18.238+0200] {logging_mixin.py:154} INFO - [2025-06-01T17:54:18.238+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-01T17:54:18.239+0200] {processor.py:841} WARNING - No viable dags retrieved from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T17:54:18.247+0200] {processor.py:179} INFO - Processing /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2025-06-01T17:55:02.645+0200] {processor.py:157} INFO - Started process (PID=27264) to work on /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T17:55:02.646+0200] {processor.py:829} INFO - Processing file /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-01T17:55:02.647+0200] {logging_mixin.py:154} INFO - [2025-06-01T17:55:02.647+0200] {dagbag.py:536} INFO - Filling up the DagBag from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T17:55:02.651+0200] {logging_mixin.py:154} INFO - [2025-06-01T17:55:02.650+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-01T17:55:02.651+0200] {logging_mixin.py:154} INFO - [2025-06-01T17:55:02.651+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-01T17:55:02.651+0200] {processor.py:841} WARNING - No viable dags retrieved from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T17:55:02.659+0200] {processor.py:179} INFO - Processing /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2025-06-01T17:55:50.646+0200] {processor.py:157} INFO - Started process (PID=27334) to work on /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T17:55:50.648+0200] {processor.py:829} INFO - Processing file /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-01T17:55:50.648+0200] {logging_mixin.py:154} INFO - [2025-06-01T17:55:50.648+0200] {dagbag.py:536} INFO - Filling up the DagBag from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T17:55:50.650+0200] {logging_mixin.py:154} INFO - [2025-06-01T17:55:50.650+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-01T17:55:50.650+0200] {logging_mixin.py:154} INFO - [2025-06-01T17:55:50.650+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-01T17:55:50.650+0200] {processor.py:841} WARNING - No viable dags retrieved from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T17:55:50.656+0200] {processor.py:179} INFO - Processing /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2025-06-01T17:56:36.085+0200] {processor.py:157} INFO - Started process (PID=27404) to work on /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T17:56:36.086+0200] {processor.py:829} INFO - Processing file /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-01T17:56:36.087+0200] {logging_mixin.py:154} INFO - [2025-06-01T17:56:36.087+0200] {dagbag.py:536} INFO - Filling up the DagBag from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T17:56:36.089+0200] {logging_mixin.py:154} INFO - [2025-06-01T17:56:36.089+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-01T17:56:36.089+0200] {logging_mixin.py:154} INFO - [2025-06-01T17:56:36.089+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-01T17:56:36.089+0200] {processor.py:841} WARNING - No viable dags retrieved from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T17:56:36.095+0200] {processor.py:179} INFO - Processing /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2025-06-01T17:57:24.473+0200] {processor.py:157} INFO - Started process (PID=27476) to work on /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T17:57:24.477+0200] {processor.py:829} INFO - Processing file /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-01T17:57:24.477+0200] {logging_mixin.py:154} INFO - [2025-06-01T17:57:24.477+0200] {dagbag.py:536} INFO - Filling up the DagBag from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T17:57:24.479+0200] {logging_mixin.py:154} INFO - [2025-06-01T17:57:24.479+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-01T17:57:24.480+0200] {logging_mixin.py:154} INFO - [2025-06-01T17:57:24.480+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-01T17:57:24.480+0200] {processor.py:841} WARNING - No viable dags retrieved from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T17:57:24.486+0200] {processor.py:179} INFO - Processing /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.014 seconds
[2025-06-01T17:58:09.371+0200] {processor.py:157} INFO - Started process (PID=27544) to work on /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T17:58:09.374+0200] {processor.py:829} INFO - Processing file /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-01T17:58:09.374+0200] {logging_mixin.py:154} INFO - [2025-06-01T17:58:09.374+0200] {dagbag.py:536} INFO - Filling up the DagBag from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T17:58:09.377+0200] {logging_mixin.py:154} INFO - [2025-06-01T17:58:09.376+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-01T17:58:09.377+0200] {logging_mixin.py:154} INFO - [2025-06-01T17:58:09.377+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-01T17:58:09.377+0200] {processor.py:841} WARNING - No viable dags retrieved from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T17:58:09.382+0200] {processor.py:179} INFO - Processing /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.014 seconds
[2025-06-01T17:58:57.772+0200] {processor.py:157} INFO - Started process (PID=27615) to work on /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T17:58:57.774+0200] {processor.py:829} INFO - Processing file /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-01T17:58:57.774+0200] {logging_mixin.py:154} INFO - [2025-06-01T17:58:57.774+0200] {dagbag.py:536} INFO - Filling up the DagBag from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T17:58:57.776+0200] {logging_mixin.py:154} INFO - [2025-06-01T17:58:57.776+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-01T17:58:57.776+0200] {logging_mixin.py:154} INFO - [2025-06-01T17:58:57.776+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-01T17:58:57.776+0200] {processor.py:841} WARNING - No viable dags retrieved from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T17:58:57.782+0200] {processor.py:179} INFO - Processing /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2025-06-01T17:59:41.762+0200] {processor.py:157} INFO - Started process (PID=27683) to work on /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T17:59:41.765+0200] {processor.py:829} INFO - Processing file /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-01T17:59:41.766+0200] {logging_mixin.py:154} INFO - [2025-06-01T17:59:41.765+0200] {dagbag.py:536} INFO - Filling up the DagBag from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T17:59:41.768+0200] {logging_mixin.py:154} INFO - [2025-06-01T17:59:41.767+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-01T17:59:41.768+0200] {logging_mixin.py:154} INFO - [2025-06-01T17:59:41.768+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-01T17:59:41.768+0200] {processor.py:841} WARNING - No viable dags retrieved from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T17:59:41.774+0200] {processor.py:179} INFO - Processing /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.014 seconds
[2025-06-01T18:00:31.427+0200] {processor.py:157} INFO - Started process (PID=27754) to work on /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:00:31.431+0200] {processor.py:829} INFO - Processing file /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-01T18:00:31.431+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:00:31.431+0200] {dagbag.py:536} INFO - Filling up the DagBag from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:00:31.433+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:00:31.433+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-01T18:00:31.433+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:00:31.433+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-01T18:00:31.434+0200] {processor.py:841} WARNING - No viable dags retrieved from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:00:31.439+0200] {processor.py:179} INFO - Processing /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.014 seconds
[2025-06-01T18:01:16.541+0200] {processor.py:157} INFO - Started process (PID=27855) to work on /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:01:16.545+0200] {processor.py:829} INFO - Processing file /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-01T18:01:16.545+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:01:16.545+0200] {dagbag.py:536} INFO - Filling up the DagBag from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:01:16.548+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:01:16.547+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-01T18:01:16.548+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:01:16.548+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-01T18:01:16.548+0200] {processor.py:841} WARNING - No viable dags retrieved from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:01:16.554+0200] {processor.py:179} INFO - Processing /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2025-06-01T18:02:05.051+0200] {processor.py:157} INFO - Started process (PID=27927) to work on /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:02:05.055+0200] {processor.py:829} INFO - Processing file /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-01T18:02:05.055+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:02:05.055+0200] {dagbag.py:536} INFO - Filling up the DagBag from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:02:05.057+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:02:05.057+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-01T18:02:05.058+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:02:05.057+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-01T18:02:05.058+0200] {processor.py:841} WARNING - No viable dags retrieved from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:02:05.065+0200] {processor.py:179} INFO - Processing /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2025-06-01T18:02:47.905+0200] {processor.py:157} INFO - Started process (PID=27995) to work on /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:02:47.908+0200] {processor.py:829} INFO - Processing file /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-01T18:02:47.909+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:02:47.909+0200] {dagbag.py:536} INFO - Filling up the DagBag from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:02:47.911+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:02:47.910+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-01T18:02:47.911+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:02:47.911+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-01T18:02:47.911+0200] {processor.py:841} WARNING - No viable dags retrieved from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:02:47.917+0200] {processor.py:179} INFO - Processing /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.014 seconds
[2025-06-01T18:03:35.354+0200] {processor.py:157} INFO - Started process (PID=28073) to work on /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:03:35.355+0200] {processor.py:829} INFO - Processing file /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-01T18:03:35.356+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:03:35.356+0200] {dagbag.py:536} INFO - Filling up the DagBag from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:03:35.358+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:03:35.358+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-01T18:03:35.359+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:03:35.358+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-01T18:03:35.359+0200] {processor.py:841} WARNING - No viable dags retrieved from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:03:35.365+0200] {processor.py:179} INFO - Processing /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2025-06-01T18:04:20.767+0200] {processor.py:157} INFO - Started process (PID=28145) to work on /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:04:20.770+0200] {processor.py:829} INFO - Processing file /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-01T18:04:20.770+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:04:20.770+0200] {dagbag.py:536} INFO - Filling up the DagBag from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:04:20.773+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:04:20.772+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-01T18:04:20.773+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:04:20.773+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-01T18:04:20.773+0200] {processor.py:841} WARNING - No viable dags retrieved from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:04:20.783+0200] {processor.py:179} INFO - Processing /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2025-06-01T18:05:07.899+0200] {processor.py:157} INFO - Started process (PID=28222) to work on /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:05:07.903+0200] {processor.py:829} INFO - Processing file /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-01T18:05:07.903+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:05:07.903+0200] {dagbag.py:536} INFO - Filling up the DagBag from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:05:07.905+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:05:07.905+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-01T18:05:07.906+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:05:07.905+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-01T18:05:07.906+0200] {processor.py:841} WARNING - No viable dags retrieved from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:05:07.912+0200] {processor.py:179} INFO - Processing /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2025-06-01T18:05:59.666+0200] {processor.py:157} INFO - Started process (PID=28303) to work on /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:05:59.667+0200] {processor.py:829} INFO - Processing file /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-01T18:05:59.668+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:05:59.668+0200] {dagbag.py:536} INFO - Filling up the DagBag from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:05:59.670+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:05:59.670+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-01T18:05:59.670+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:05:59.670+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-01T18:05:59.670+0200] {processor.py:841} WARNING - No viable dags retrieved from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:05:59.677+0200] {processor.py:179} INFO - Processing /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2025-06-01T18:06:43.079+0200] {processor.py:157} INFO - Started process (PID=28371) to work on /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:06:43.081+0200] {processor.py:829} INFO - Processing file /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-01T18:06:43.081+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:06:43.081+0200] {dagbag.py:536} INFO - Filling up the DagBag from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:06:43.084+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:06:43.083+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-01T18:06:43.084+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:06:43.084+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-01T18:06:43.084+0200] {processor.py:841} WARNING - No viable dags retrieved from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:06:43.090+0200] {processor.py:179} INFO - Processing /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.013 seconds
[2025-06-01T18:07:29.208+0200] {processor.py:157} INFO - Started process (PID=28439) to work on /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:07:29.209+0200] {processor.py:829} INFO - Processing file /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-01T18:07:29.210+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:07:29.209+0200] {dagbag.py:536} INFO - Filling up the DagBag from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:07:29.212+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:07:29.211+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-01T18:07:29.212+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:07:29.212+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-01T18:07:29.212+0200] {processor.py:841} WARNING - No viable dags retrieved from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:07:29.220+0200] {processor.py:179} INFO - Processing /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.014 seconds
[2025-06-01T18:08:13.659+0200] {processor.py:157} INFO - Started process (PID=28507) to work on /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:08:13.661+0200] {processor.py:829} INFO - Processing file /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-01T18:08:13.661+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:08:13.661+0200] {dagbag.py:536} INFO - Filling up the DagBag from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:08:13.663+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:08:13.663+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-01T18:08:13.663+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:08:13.663+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-01T18:08:13.664+0200] {processor.py:841} WARNING - No viable dags retrieved from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:08:13.670+0200] {processor.py:179} INFO - Processing /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2025-06-01T18:09:05.726+0200] {processor.py:157} INFO - Started process (PID=28586) to work on /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:09:05.730+0200] {processor.py:829} INFO - Processing file /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-01T18:09:05.730+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:09:05.730+0200] {dagbag.py:536} INFO - Filling up the DagBag from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:09:05.732+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:09:05.732+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-01T18:09:05.732+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:09:05.732+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-01T18:09:05.733+0200] {processor.py:841} WARNING - No viable dags retrieved from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:09:05.738+0200] {processor.py:179} INFO - Processing /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.014 seconds
[2025-06-01T18:09:52.938+0200] {processor.py:157} INFO - Started process (PID=28665) to work on /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:09:52.941+0200] {processor.py:829} INFO - Processing file /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-01T18:09:52.942+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:09:52.941+0200] {dagbag.py:536} INFO - Filling up the DagBag from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:09:52.944+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:09:52.943+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-01T18:09:52.944+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:09:52.944+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-01T18:09:52.944+0200] {processor.py:841} WARNING - No viable dags retrieved from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:09:52.951+0200] {processor.py:179} INFO - Processing /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2025-06-01T18:10:41.827+0200] {processor.py:157} INFO - Started process (PID=28740) to work on /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:10:41.831+0200] {processor.py:829} INFO - Processing file /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-01T18:10:41.832+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:10:41.831+0200] {dagbag.py:536} INFO - Filling up the DagBag from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:10:41.835+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:10:41.834+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-01T18:10:41.835+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:10:41.835+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-01T18:10:41.835+0200] {processor.py:841} WARNING - No viable dags retrieved from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:10:41.842+0200] {processor.py:179} INFO - Processing /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2025-06-01T18:11:28.143+0200] {processor.py:157} INFO - Started process (PID=28810) to work on /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:11:28.144+0200] {processor.py:829} INFO - Processing file /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-01T18:11:28.145+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:11:28.145+0200] {dagbag.py:536} INFO - Filling up the DagBag from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:11:28.147+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:11:28.147+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-01T18:11:28.147+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:11:28.147+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-01T18:11:28.147+0200] {processor.py:841} WARNING - No viable dags retrieved from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:11:28.153+0200] {processor.py:179} INFO - Processing /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2025-06-01T18:12:21.613+0200] {processor.py:157} INFO - Started process (PID=28892) to work on /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:12:21.616+0200] {processor.py:829} INFO - Processing file /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-01T18:12:21.617+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:12:21.617+0200] {dagbag.py:536} INFO - Filling up the DagBag from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:12:21.619+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:12:21.619+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-01T18:12:21.619+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:12:21.619+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-01T18:12:21.619+0200] {processor.py:841} WARNING - No viable dags retrieved from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:12:21.626+0200] {processor.py:179} INFO - Processing /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2025-06-01T18:13:10.701+0200] {processor.py:157} INFO - Started process (PID=28963) to work on /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:13:10.704+0200] {processor.py:829} INFO - Processing file /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-01T18:13:10.705+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:13:10.704+0200] {dagbag.py:536} INFO - Filling up the DagBag from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:13:10.707+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:13:10.707+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-01T18:13:10.707+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:13:10.707+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-01T18:13:10.707+0200] {processor.py:841} WARNING - No viable dags retrieved from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:13:10.714+0200] {processor.py:179} INFO - Processing /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2025-06-01T18:13:54.581+0200] {processor.py:157} INFO - Started process (PID=29032) to work on /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:13:54.585+0200] {processor.py:829} INFO - Processing file /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-01T18:13:54.586+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:13:54.586+0200] {dagbag.py:536} INFO - Filling up the DagBag from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:13:54.589+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:13:54.589+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-01T18:13:54.589+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:13:54.589+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-01T18:13:54.589+0200] {processor.py:841} WARNING - No viable dags retrieved from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:13:54.596+0200] {processor.py:179} INFO - Processing /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2025-06-01T18:14:37.002+0200] {processor.py:157} INFO - Started process (PID=29098) to work on /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:14:37.006+0200] {processor.py:829} INFO - Processing file /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-01T18:14:37.006+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:14:37.006+0200] {dagbag.py:536} INFO - Filling up the DagBag from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:14:37.009+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:14:37.008+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-01T18:14:37.009+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:14:37.009+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-01T18:14:37.009+0200] {processor.py:841} WARNING - No viable dags retrieved from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:14:37.018+0200] {processor.py:179} INFO - Processing /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2025-06-01T18:15:26.663+0200] {processor.py:157} INFO - Started process (PID=29169) to work on /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:15:26.667+0200] {processor.py:829} INFO - Processing file /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-01T18:15:26.667+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:15:26.667+0200] {dagbag.py:536} INFO - Filling up the DagBag from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:15:26.670+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:15:26.669+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-01T18:15:26.670+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:15:26.670+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-01T18:15:26.670+0200] {processor.py:841} WARNING - No viable dags retrieved from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:15:26.677+0200] {processor.py:179} INFO - Processing /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2025-06-01T18:16:15.785+0200] {processor.py:157} INFO - Started process (PID=29242) to work on /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:16:15.787+0200] {processor.py:829} INFO - Processing file /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-01T18:16:15.788+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:16:15.787+0200] {dagbag.py:536} INFO - Filling up the DagBag from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:16:15.790+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:16:15.790+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-01T18:16:15.790+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:16:15.790+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-01T18:16:15.791+0200] {processor.py:841} WARNING - No viable dags retrieved from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:16:15.797+0200] {processor.py:179} INFO - Processing /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.014 seconds
[2025-06-01T18:17:02.786+0200] {processor.py:157} INFO - Started process (PID=29315) to work on /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:17:02.789+0200] {processor.py:829} INFO - Processing file /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-01T18:17:02.790+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:17:02.790+0200] {dagbag.py:536} INFO - Filling up the DagBag from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:17:02.792+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:17:02.792+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-01T18:17:02.792+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:17:02.792+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-01T18:17:02.792+0200] {processor.py:841} WARNING - No viable dags retrieved from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:17:02.798+0200] {processor.py:179} INFO - Processing /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.014 seconds
[2025-06-01T18:17:48.172+0200] {processor.py:157} INFO - Started process (PID=29384) to work on /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:17:48.176+0200] {processor.py:829} INFO - Processing file /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-01T18:17:48.176+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:17:48.176+0200] {dagbag.py:536} INFO - Filling up the DagBag from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:17:48.179+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:17:48.178+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-01T18:17:48.179+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:17:48.179+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-01T18:17:48.179+0200] {processor.py:841} WARNING - No viable dags retrieved from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:17:48.185+0200] {processor.py:179} INFO - Processing /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2025-06-01T18:18:32.346+0200] {processor.py:157} INFO - Started process (PID=29451) to work on /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:18:32.350+0200] {processor.py:829} INFO - Processing file /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-01T18:18:32.351+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:18:32.351+0200] {dagbag.py:536} INFO - Filling up the DagBag from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:18:32.353+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:18:32.353+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-01T18:18:32.354+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:18:32.353+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-01T18:18:32.354+0200] {processor.py:841} WARNING - No viable dags retrieved from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:18:32.360+0200] {processor.py:179} INFO - Processing /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2025-06-01T18:19:18.872+0200] {processor.py:157} INFO - Started process (PID=29520) to work on /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:19:18.875+0200] {processor.py:829} INFO - Processing file /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-01T18:19:18.876+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:19:18.876+0200] {dagbag.py:536} INFO - Filling up the DagBag from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:19:18.878+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:19:18.878+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-01T18:19:18.878+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:19:18.878+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-01T18:19:18.879+0200] {processor.py:841} WARNING - No viable dags retrieved from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:19:18.885+0200] {processor.py:179} INFO - Processing /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2025-06-01T18:20:07.393+0200] {processor.py:157} INFO - Started process (PID=29591) to work on /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:20:07.397+0200] {processor.py:829} INFO - Processing file /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-01T18:20:07.397+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:20:07.397+0200] {dagbag.py:536} INFO - Filling up the DagBag from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:20:07.400+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:20:07.399+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-01T18:20:07.400+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:20:07.400+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-01T18:20:07.400+0200] {processor.py:841} WARNING - No viable dags retrieved from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:20:07.407+0200] {processor.py:179} INFO - Processing /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2025-06-01T18:20:56.456+0200] {processor.py:157} INFO - Started process (PID=29662) to work on /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:20:56.460+0200] {processor.py:829} INFO - Processing file /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-01T18:20:56.461+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:20:56.460+0200] {dagbag.py:536} INFO - Filling up the DagBag from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:20:56.464+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:20:56.464+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-01T18:20:56.464+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:20:56.464+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-01T18:20:56.464+0200] {processor.py:841} WARNING - No viable dags retrieved from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:20:56.471+0200] {processor.py:179} INFO - Processing /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2025-06-01T18:21:44.776+0200] {processor.py:157} INFO - Started process (PID=29733) to work on /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:21:44.779+0200] {processor.py:829} INFO - Processing file /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-01T18:21:44.780+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:21:44.780+0200] {dagbag.py:536} INFO - Filling up the DagBag from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:21:44.782+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:21:44.782+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-01T18:21:44.782+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:21:44.782+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-01T18:21:44.782+0200] {processor.py:841} WARNING - No viable dags retrieved from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:21:44.788+0200] {processor.py:179} INFO - Processing /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.014 seconds
[2025-06-01T18:22:29.899+0200] {processor.py:157} INFO - Started process (PID=29802) to work on /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:22:29.903+0200] {processor.py:829} INFO - Processing file /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-01T18:22:29.903+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:22:29.903+0200] {dagbag.py:536} INFO - Filling up the DagBag from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:22:29.905+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:22:29.905+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-01T18:22:29.905+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:22:29.905+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-01T18:22:29.906+0200] {processor.py:841} WARNING - No viable dags retrieved from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:22:29.914+0200] {processor.py:179} INFO - Processing /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2025-06-01T18:23:19.935+0200] {processor.py:157} INFO - Started process (PID=29873) to work on /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:23:19.939+0200] {processor.py:829} INFO - Processing file /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-01T18:23:19.940+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:23:19.939+0200] {dagbag.py:536} INFO - Filling up the DagBag from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:23:19.943+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:23:19.942+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-01T18:23:19.943+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:23:19.943+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-01T18:23:19.943+0200] {processor.py:841} WARNING - No viable dags retrieved from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:23:19.949+0200] {processor.py:179} INFO - Processing /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2025-06-01T18:24:06.632+0200] {processor.py:157} INFO - Started process (PID=29944) to work on /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:24:06.635+0200] {processor.py:829} INFO - Processing file /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-01T18:24:06.635+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:24:06.635+0200] {dagbag.py:536} INFO - Filling up the DagBag from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:24:06.637+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:24:06.637+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-01T18:24:06.637+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:24:06.637+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-01T18:24:06.638+0200] {processor.py:841} WARNING - No viable dags retrieved from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:24:06.644+0200] {processor.py:179} INFO - Processing /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2025-06-01T18:24:54.019+0200] {processor.py:157} INFO - Started process (PID=30013) to work on /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:24:54.022+0200] {processor.py:829} INFO - Processing file /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-01T18:24:54.023+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:24:54.023+0200] {dagbag.py:536} INFO - Filling up the DagBag from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:24:54.025+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:24:54.025+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-01T18:24:54.025+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:24:54.025+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-01T18:24:54.025+0200] {processor.py:841} WARNING - No viable dags retrieved from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:24:54.031+0200] {processor.py:179} INFO - Processing /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.014 seconds
[2025-06-01T18:25:42.758+0200] {processor.py:157} INFO - Started process (PID=30084) to work on /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:25:42.762+0200] {processor.py:829} INFO - Processing file /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-01T18:25:42.762+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:25:42.762+0200] {dagbag.py:536} INFO - Filling up the DagBag from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:25:42.764+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:25:42.764+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-01T18:25:42.764+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:25:42.764+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-01T18:25:42.764+0200] {processor.py:841} WARNING - No viable dags retrieved from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:25:42.771+0200] {processor.py:179} INFO - Processing /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2025-06-01T18:26:26.311+0200] {processor.py:157} INFO - Started process (PID=30153) to work on /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:26:26.313+0200] {processor.py:829} INFO - Processing file /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-01T18:26:26.314+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:26:26.313+0200] {dagbag.py:536} INFO - Filling up the DagBag from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:26:26.316+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:26:26.315+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-01T18:26:26.316+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:26:26.316+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-01T18:26:26.316+0200] {processor.py:841} WARNING - No viable dags retrieved from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:26:26.322+0200] {processor.py:179} INFO - Processing /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.013 seconds
[2025-06-01T18:27:14.005+0200] {processor.py:157} INFO - Started process (PID=30224) to work on /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:27:14.006+0200] {processor.py:829} INFO - Processing file /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-01T18:27:14.007+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:27:14.007+0200] {dagbag.py:536} INFO - Filling up the DagBag from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:27:14.009+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:27:14.009+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-01T18:27:14.009+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:27:14.009+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-01T18:27:14.009+0200] {processor.py:841} WARNING - No viable dags retrieved from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:27:14.017+0200] {processor.py:179} INFO - Processing /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.014 seconds
[2025-06-01T18:27:59.427+0200] {processor.py:157} INFO - Started process (PID=30292) to work on /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:27:59.431+0200] {processor.py:829} INFO - Processing file /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-01T18:27:59.431+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:27:59.431+0200] {dagbag.py:536} INFO - Filling up the DagBag from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:27:59.434+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:27:59.433+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-01T18:27:59.434+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:27:59.434+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-01T18:27:59.434+0200] {processor.py:841} WARNING - No viable dags retrieved from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:27:59.441+0200] {processor.py:179} INFO - Processing /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2025-06-01T18:28:49.481+0200] {processor.py:157} INFO - Started process (PID=30364) to work on /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:28:49.482+0200] {processor.py:829} INFO - Processing file /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-01T18:28:49.483+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:28:49.483+0200] {dagbag.py:536} INFO - Filling up the DagBag from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:28:49.485+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:28:49.485+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-01T18:28:49.485+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:28:49.485+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-01T18:28:49.486+0200] {processor.py:841} WARNING - No viable dags retrieved from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:28:49.493+0200] {processor.py:179} INFO - Processing /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.014 seconds
[2025-06-01T18:29:32.992+0200] {processor.py:157} INFO - Started process (PID=30431) to work on /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:29:32.994+0200] {processor.py:829} INFO - Processing file /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-01T18:29:32.994+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:29:32.994+0200] {dagbag.py:536} INFO - Filling up the DagBag from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:29:32.997+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:29:32.997+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-01T18:29:32.997+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:29:32.997+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-01T18:29:32.997+0200] {processor.py:841} WARNING - No viable dags retrieved from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:29:33.007+0200] {processor.py:179} INFO - Processing /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2025-06-01T18:30:18.032+0200] {processor.py:157} INFO - Started process (PID=30500) to work on /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:30:18.034+0200] {processor.py:829} INFO - Processing file /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-01T18:30:18.034+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:30:18.034+0200] {dagbag.py:536} INFO - Filling up the DagBag from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:30:18.037+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:30:18.036+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-01T18:30:18.037+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:30:18.037+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-01T18:30:18.037+0200] {processor.py:841} WARNING - No viable dags retrieved from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:30:18.044+0200] {processor.py:179} INFO - Processing /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.014 seconds
[2025-06-01T18:30:59.994+0200] {processor.py:157} INFO - Started process (PID=30546) to work on /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:30:59.998+0200] {processor.py:829} INFO - Processing file /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-01T18:30:59.999+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:30:59.999+0200] {dagbag.py:536} INFO - Filling up the DagBag from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:31:00.002+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:31:00.001+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-01T18:31:00.002+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:31:00.002+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-01T18:31:00.002+0200] {processor.py:841} WARNING - No viable dags retrieved from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:31:00.010+0200] {processor.py:179} INFO - Processing /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2025-06-01T18:31:45.482+0200] {processor.py:157} INFO - Started process (PID=30615) to work on /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:31:45.483+0200] {processor.py:829} INFO - Processing file /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-01T18:31:45.484+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:31:45.484+0200] {dagbag.py:536} INFO - Filling up the DagBag from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:31:45.486+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:31:45.486+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-01T18:31:45.486+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:31:45.486+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-01T18:31:45.487+0200] {processor.py:841} WARNING - No viable dags retrieved from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:31:45.493+0200] {processor.py:179} INFO - Processing /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.013 seconds
[2025-06-01T18:32:30.683+0200] {processor.py:157} INFO - Started process (PID=30683) to work on /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:32:30.687+0200] {processor.py:829} INFO - Processing file /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-01T18:32:30.687+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:32:30.687+0200] {dagbag.py:536} INFO - Filling up the DagBag from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:32:30.690+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:32:30.689+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-01T18:32:30.690+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:32:30.690+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-01T18:32:30.690+0200] {processor.py:841} WARNING - No viable dags retrieved from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:32:30.696+0200] {processor.py:179} INFO - Processing /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2025-06-01T18:33:14.346+0200] {processor.py:157} INFO - Started process (PID=30751) to work on /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:33:14.349+0200] {processor.py:829} INFO - Processing file /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-01T18:33:14.350+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:33:14.350+0200] {dagbag.py:536} INFO - Filling up the DagBag from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:33:14.352+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:33:14.352+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-01T18:33:14.353+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:33:14.353+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-01T18:33:14.353+0200] {processor.py:841} WARNING - No viable dags retrieved from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:33:14.359+0200] {processor.py:179} INFO - Processing /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2025-06-01T18:34:06.782+0200] {processor.py:157} INFO - Started process (PID=30824) to work on /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:34:06.785+0200] {processor.py:829} INFO - Processing file /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-01T18:34:06.786+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:34:06.786+0200] {dagbag.py:536} INFO - Filling up the DagBag from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:34:06.788+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:34:06.788+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-01T18:34:06.789+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:34:06.789+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-01T18:34:06.789+0200] {processor.py:841} WARNING - No viable dags retrieved from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:34:06.795+0200] {processor.py:179} INFO - Processing /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2025-06-01T18:34:52.953+0200] {processor.py:157} INFO - Started process (PID=31609) to work on /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:34:52.954+0200] {processor.py:829} INFO - Processing file /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-01T18:34:52.955+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:34:52.955+0200] {dagbag.py:536} INFO - Filling up the DagBag from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:34:52.957+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:34:52.957+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-01T18:34:52.957+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:34:52.957+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-01T18:34:52.957+0200] {processor.py:841} WARNING - No viable dags retrieved from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:34:52.964+0200] {processor.py:179} INFO - Processing /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.014 seconds
[2025-06-01T18:35:41.781+0200] {processor.py:157} INFO - Started process (PID=31680) to work on /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:35:41.782+0200] {processor.py:829} INFO - Processing file /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-01T18:35:41.783+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:35:41.782+0200] {dagbag.py:536} INFO - Filling up the DagBag from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:35:41.786+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:35:41.785+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-01T18:35:41.786+0200] {logging_mixin.py:154} INFO - [2025-06-01T18:35:41.786+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-01T18:35:41.786+0200] {processor.py:841} WARNING - No viable dags retrieved from /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-01T18:35:41.795+0200] {processor.py:179} INFO - Processing /home/lohit/miniconda3/envs/airflow-env/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
